package com.sysnet.poc.control.manage.vo;

public class EtlPharosIncrAcc {

	/**
	 * EtlPharosIncrAcc generated by Sysnet Persistence Tools
	 */

	private Long objectId;
	private String objectNo;
	private Long objectType;
	private Long batId;
	private String contractNo;
	private String nodeNo;
	private String assistCode;
	private java.sql.Date timeStamp;
	private String dealFlag;
	private String stageWriteFlag;
	private String odsWriteFlag;
	private Boolean isClaim;

	public Boolean getIsClaim() {
		return isClaim;
	}

	public void setIsClaim(Boolean isClaim) {
		this.isClaim = isClaim;
	}

	public EtlPharosIncrAcc() {
	}

	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	public Long getObjectId() {
		return this.objectId;
	}

	public void setObjectNo(String objectNo) {
		this.objectNo = objectNo;
	}

	public String getObjectNo() {
		return this.objectNo;
	}

	public void setObjectType(Long objectType) {
		this.objectType = objectType;
	}

	public Long getObjectType() {
		return this.objectType;
	}

	public void setBatId(Long batId) {
		this.batId = batId;
	}

	public Long getBatId() {
		return this.batId;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public String getContractNo() {
		return this.contractNo;
	}

	public void setNodeNo(String nodeNo) {
		this.nodeNo = nodeNo;
	}

	public String getNodeNo() {
		return this.nodeNo;
	}

	public void setAssistCode(String assistCode) {
		this.assistCode = assistCode;
	}

	public String getAssistCode() {
		return this.assistCode;
	}

	public void setTimeStamp(java.sql.Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public java.sql.Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setDealFlag(String dealFlag) {
		this.dealFlag = dealFlag;
	}

	public String getDealFlag() {
		return this.dealFlag;
	}

	public void setStageWriteFlag(String stageWriteFlag) {
		this.stageWriteFlag = stageWriteFlag;
	}

	public String getStageWriteFlag() {
		return this.stageWriteFlag;
	}

	public void setOdsWriteFlag(String odsWriteFlag) {
		this.odsWriteFlag = odsWriteFlag;
	}

	public String getOdsWriteFlag() {
		return this.odsWriteFlag;
	}

}
