package com.sysnet.poc.service.dao;

/**
 * ClaimDAO generated by Sysnet Persistence Tools
 */

import java.sql.Connection;
import java.sql.SQLException;

import com.sysnet.poc.control.manage.vo.EtlPharosIncrClaim;

public interface ClaimDAO {

	public void setOdsConn(Connection conn) throws SQLException;

	public void setPharosConn(Connection conn) throws SQLException;

	/**
	 * 更新理赔增量表
	 */
	public void updateIncr(EtlPharosIncrClaim ic) throws SQLException;

	public void deleteAllTableOfClaimByCI(Long claimId) throws SQLException;
}