package com.sysnet.poc.service.dao.impl;

/**
 * ClaimDAOimpl generated by Sysnet Persistence Tools
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import com.sysnet.poc.control.config.Constants;
import com.sysnet.poc.control.manage.vo.EtlPharosIncrClaim;
import com.sysnet.poc.service.dao.ClaimDAO;
import com.sysnet.poc.util.ResourceBundleUtil;

public class ClaimDAOimpl implements ClaimDAO {

	private Connection odsConn = null;
	private Connection pharosConn = null;
	private PreparedStatement ps = null;

	public void setOdsConn(Connection conn) throws SQLException {
		this.odsConn = conn;
	}

	public void setPharosConn(Connection conn) throws SQLException {
		this.pharosConn = conn;
	}

	public void deleteAllTableOfClaimByCI(Long claimId) throws SQLException {
		String sql = "";
		sql = "delete from stg_clm_fee_detail where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_transaction_detail where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_consequences where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_claim_transaction where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_loss_file where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_part_of_claim where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_in_hospital where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_disability where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_regist where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_claim where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_in_operation where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_clinic where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
		sql = "delete from stg_clm_claim_role_info where claim_id=?";
		ps = odsConn.prepareStatement(sql);
		ps.setLong(1, claimId);
		ps.executeUpdate();
		ps.close();
	}

	public void updateIncr(EtlPharosIncrClaim ic) throws SQLException {// 这里为了偷懒，即直接传个对象过来，以后就不用每个字段都改了，与hibernate一样
		String sql = "update " 
				+ Constants.ETL_PHAROS_INCR_CLAIM 
				+ ResourceBundleUtil.readValue("riskNodeThreads") 
				+ " set OBJECT_NO=?," + "OBJECT_TYPE=?," + "BAT_ID=?," + "CONTRACT_NO=?," + "NODE_ID=?," 
				+ "ASSIST_CODE=?," + "TIME_STAMP=?," + "DEAL_FLAG=?," + "STAGE_WRITE_FLAG=?," + "ODS_WRITE_FLAG=?," 
				+ "ACTIVITYID=?," + "ACTIVITYNAME=?," + "PROCESSID=?," + "ACTIVITYTYPE=?," + "TRANSACTIONTYPE=?," 
				+ "PROPOSALID=?," + "PROPOSALNODEID=?," + "PROPOSALNO=?," + "CONTRACTNO=?," 
				+ "NODENO=?," + "CLAIMID=?," + "PARTCLAIMID=? "
				+ "where OBJECT_ID=?";
		ps = pharosConn.prepareStatement(sql);
		ps.setString(1, ic.getObjectNo());
		ps.setLong(2, ic.getObjectType());
		ps.setLong(3, ic.getBatId());
		ps.setString(4, ic.getContractNo());
		ps.setLong(5, ic.getNodeId());
		ps.setString(6, ic.getAssistCode());
		ps.setTimestamp(7, ic.getTimeStamp());
		ps.setString(8, ic.getDealFlag());
		ps.setString(9, ic.getStageWriteFlag());
		ps.setString(10, ic.getOdsWriteFlag());
		ps.setLong(11, ic.getActivityId());
		ps.setString(12, ic.getActivityName());
		ps.setLong(13, ic.getProcessId());
		ps.setLong(14, ic.getActivityType());
		ps.setString(15, ic.getTransactionType());
		ps.setLong(16, ic.getProposalId());
		ps.setLong(17, ic.getProposalNodeId());
		ps.setString(18, ic.getProposalNo());
		ps.setString(19, ic.getPolicNo());
		ps.setString(20, ic.getNodeNo());
		ps.setLong(21, ic.getClaimId());
		ps.setLong(22, ic.getPartClaimId());
		ps.setLong(23, ic.getObjectId());
		ps.executeUpdate();
		ps.close();
	}
}