package com.sysnet.poc.control.manage.vo;

/**
 * EtlPharosIncrWorkflow generated by Sysnet Persistence Tools
 */

public class EtlPharosIncrWorkflow {

	private Long objectId = 0L;
	private String objectNo = "";
	private Short objectType = 0;
	private Long batId = 0L;
	private String contractNo = "";
	private Long nodeId = 0L;
	private String assistCode = "";
	private java.sql.Timestamp timeStamp = null;
	private String dealFlag = "";
	private String stageWriteFlag = "";
	private String odsWriteFlag = "";
	private Long activityid = 0L;
	private String activityname = "";
	private Long processid = 0L;
	private Long activitytype = 0L;
	private Long transactiontype = 0L;
	private Long proposalid = 0L;
	private Long proposalnodeid = 0L;
	private String proposalno = "";
	private String contractno = "";
	private String nodeno = "";
	private Long claimid = 0L;
	private Long partclaimid = 0L;
	private Long dactivityid = 0L;

	public EtlPharosIncrWorkflow() {
	}

	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	public Long getObjectId() {
		return this.objectId;
	}

	public void setObjectNo(String objectNo) {
		this.objectNo = objectNo;
	}

	public String getObjectNo() {
		return this.objectNo;
	}

	public void setObjectType(Short objectType) {
		this.objectType = objectType;
	}

	public Short getObjectType() {
		return this.objectType;
	}

	public void setBatId(Long batId) {
		this.batId = batId;
	}

	public Long getBatId() {
		return this.batId;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public String getContractNo() {
		return this.contractNo;
	}

	public void setNodeId(Long nodeId) {
		this.nodeId = nodeId;
	}

	public Long getNodeId() {
		return this.nodeId;
	}

	public void setAssistCode(String assistCode) {
		this.assistCode = assistCode;
	}

	public String getAssistCode() {
		return this.assistCode;
	}

	public void setTimeStamp(java.sql.Timestamp timeStamp) {
		this.timeStamp = timeStamp;
	}

	public java.sql.Timestamp getTimeStamp() {
		return this.timeStamp;
	}

	public void setDealFlag(String dealFlag) {
		this.dealFlag = dealFlag;
	}

	public String getDealFlag() {
		return this.dealFlag;
	}

	public void setStageWriteFlag(String stageWriteFlag) {
		this.stageWriteFlag = stageWriteFlag;
	}

	public String getStageWriteFlag() {
		return this.stageWriteFlag;
	}

	public void setOdsWriteFlag(String odsWriteFlag) {
		this.odsWriteFlag = odsWriteFlag;
	}

	public String getOdsWriteFlag() {
		return this.odsWriteFlag;
	}

	public void setActivityid(Long activityid) {
		this.activityid = activityid;
	}

	public Long getActivityid() {
		return this.activityid;
	}

	public void setActivityname(String activityname) {
		this.activityname = activityname;
	}

	public String getActivityname() {
		return this.activityname;
	}

	public void setProcessid(Long processid) {
		this.processid = processid;
	}

	public Long getProcessid() {
		return this.processid;
	}

	public void setActivitytype(Long activitytype) {
		this.activitytype = activitytype;
	}

	public Long getActivitytype() {
		return this.activitytype;
	}

	public void setTransactiontype(Long transactiontype) {
		this.transactiontype = transactiontype;
	}

	public Long getTransactiontype() {
		return this.transactiontype;
	}

	public void setProposalid(Long proposalid) {
		this.proposalid = proposalid;
	}

	public Long getProposalid() {
		return this.proposalid;
	}

	public void setProposalnodeid(Long proposalnodeid) {
		this.proposalnodeid = proposalnodeid;
	}

	public Long getProposalnodeid() {
		return this.proposalnodeid;
	}

	public void setProposalno(String proposalno) {
		this.proposalno = proposalno;
	}

	public String getProposalno() {
		return this.proposalno;
	}

	public void setContractno(String contractno) {
		this.contractno = contractno;
	}

	public String getContractno() {
		return this.contractno;
	}

	public void setNodeno(String nodeno) {
		this.nodeno = nodeno;
	}

	public String getNodeno() {
		return this.nodeno;
	}

	public void setClaimid(Long claimid) {
		this.claimid = claimid;
	}

	public Long getClaimid() {
		return this.claimid;
	}

	public void setPartclaimid(Long partclaimid) {
		this.partclaimid = partclaimid;
	}

	public Long getPartclaimid() {
		return this.partclaimid;
	}

	public void setDactivityid(Long dactivityid) {
		this.dactivityid = dactivityid;
	}

	public Long getDactivityid() {
		return this.dactivityid;
	}

}
